feat(bootstrap): Enable shasum verification, even if I won't use that

diff --git a/bootstrap/xps13-9380-install/installer b/bootstrap/xps13-9380-install/installer
--- a/bootstrap/xps13-9380-install/installer
+++ b/bootstrap/xps13-9380-install/installer
@@ -7,11 +7,11 @@ function execute_download() {
   wget "${file_url}" -O "${file_path}" || exit 255
   chmod +x "${file_path}" || exit 255
 
-  # echo "${file_sha256sum} ${file_path}" | sha256sum -c - >/dev/null 2>&1
-  # if [[ $? -ne 0 ]]; then
-  #   echo >&2 "Checksum verification failed for ${file_path}."
-  #   exit 255
-  # fi
+  echo "${file_sha256sum} ${file_path}" | sha256sum -c - >/dev/null 2>&1
+  if [[ $? -ne 0 ]]; then
+    echo >&2 "Checksum verification failed for ${file_path}."
+    exit 255
+  fi
 
 }
 
